search Auth0 users by matching an exact email
dataloom/datastore pull request #123
Opened 2017-02-24 22:49 UTC by UnsungHero97

2017-02-27 07:32 UTC, geekbeast requested changes

2017-02-27 07:32 UTC, geekbeast commented on src/main/java/com/dataloom/datastore/directory/controllers/PrincipalDirectoryController.java
> +        String exactEmailSearchQuery = "email.raw:\"" + emailSearchQuery + "\"";
This is definitely the wrong space to build this query.  Did you try using email.raw as a query param?

2017-02-27 17:52 UTC, UnsungHero97 commented on src/main/java/com/dataloom/datastore/directory/controllers/PrincipalDirectoryController.java
> +        String exactEmailSearchQuery = "email.raw:\"" + emailSearchQuery + "\"";
Where does this belong?

This `exactEmailSearchQuery` * **is** * the query param. Passing this into `userDirectoryService.searchAllUsers()` becomes `GET	/api/v2/users?q=email.raw:"foo@bar.com"`, which is what we want for searching by an exact email:

https://auth0.com/docs/api/management/v2/user-search#search-by-email

2017-02-28 02:30 UTC, geekbeast approved these changes

2017-02-28 10:04 UTC, merged