Feature/track latest sync ids
dataloom/datastore pull request #148
Opened 2017-03-23 21:18 UTC by katherinebernstein

2017-03-23 21:46 UTC, hochung approved these changes

2017-03-28 23:01 UTC, UnsungHero97 commented
The build is failing. Please look into it:

https://bamboo.thedataloom.com/browse/LOOM-DATA267-JOB1-6

2017-03-28 23:02 UTC, UnsungHero97 requested changes
The build is failing. Please look into it:

https://bamboo.thedataloom.com/browse/LOOM-DATA267-JOB1-6

2017-03-28 23:02 UTC, katherinebernstein commented
@UnsungHero97 it's because the conductor-client branch hasn't merged yet.

2017-04-10 21:26 UTC, closed without merging