LATTICE-1855 add endpoint to get multiple entitysetids by their names
dataloom/datastore pull request #360
Opened 2019-03-14 23:55 UTC by you-leee

2019-03-15 19:53 UTC, katherinebernstein requested changes

2019-03-15 19:53 UTC, katherinebernstein commented on src/main/java/com/openlattice/datastore/edm/controllers/EdmController.java
> +        return entitySetNames.stream().collect( Collectors.toMap( Function.identity(), this::getEntitySetId ) );
It would be better to bulk the calls to hazelcast

2019-03-16 00:11 UTC, geekbeast requested changes

2019-03-16 00:11 UTC, geekbeast commented on src/main/java/com/openlattice/datastore/edm/controllers/EdmController.java
> +        final Map<String, UUID> entitySetIds = modelService.getAclsByName( entitySetNames );
Waiting on rename from conductor client

2019-03-16 00:12 UTC, merged