Fix/warnings
dataloom/datastore pull request #453
Opened 2019-11-28 01:20 UTC by makosblade

This PR:
- Fixes a bunch of mechanical warnings
- Removing unused imports
- Removing unnecessary boxing/unboxing
- Uses singletonList for one-element lists
- Uses Java classes instead of Guava for functional constructs
- Fixes compiler warnings for upgrading from Java 5 through Java 8

2019-11-28 01:24 UTC, katherinebernstein approved these changes

2019-11-28 04:44 UTC, geekbeast commented on src/main/java/com/openlattice/controllers/OrganizationsController.java
> +                .filter( o -> o != null ).collect( Collectors.toSet() );
Objects::nonNull

2019-11-28 04:46 UTC, geekbeast requested changes
Minor consistency feedback.

2019-12-01 20:03 UTC, geekbeast approved these changes

2019-12-01 20:03 UTC, merged