invalidate principals cache before syncing user (not after)
dataloom/datastore pull request #463
Opened 2019-12-14 01:01 UTC by katherinebernstein

2019-12-14 01:01 UTC, you-leee approved these changes

2019-12-14 01:27 UTC, pckeyes approved these changes

2019-12-14 01:36 UTC, makosblade approved these changes

2019-12-14 22:43 UTC, geekbeast commented
After some further though syncUser always invalidates the principals cache, so that call can be removed entirely. In addition, we should pipe whether any enrollments or organization changes were made as part of syncUser. In addition, we should also invalidate the cache when a role change happens in the organization service, so quite a bit left to do.

2019-12-15 19:33 UTC, geekbeast requested changes
Just remove invalidation line entirely.

2019-12-15 20:14 UTC, geekbeast approved these changes

2019-12-15 20:15 UTC, merged