fix datastore compile
dataloom/datastore pull request #532
Opened 2020-07-30 04:21 UTC by katherinebernstein

2020-07-30 15:24 UTC, makosblade approved these changes

2020-07-30 21:23 UTC, jokedurnez approved these changes

2020-08-01 00:54 UTC, makosblade requested changes
TABS 😬 !!!

2020-08-01 00:54 UTC, makosblade approved these changes

2020-08-01 00:55 UTC, makosblade commented
> TABS 😬 !!!

I was wrong, there *were* tabs

2020-08-01 02:45 UTC, geekbeast approved these changes

2020-08-01 03:12 UTC, merged

2020-08-01 03:12 UTC, geekbeast requested changes

2020-08-01 03:12 UTC, geekbeast commented on src/test/java/com/openlattice/datastore/test/HazelcastTestHarness.java
>  public class HazelcastTestHarness {
We should be able to just delete this file and anything like this should a best a util in test.